[theme]
primaryColor = "#e23744"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f2"
textColor = "#2d2d2d"
font = "sans-serif"

[server]
headless = false
enableCORS = false
port = 8501
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false
